# Generated by Django 2.2.1 on 2019-05-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('sumOfCurrentAssets', models.IntegerField()),
                ('sumOfNonCurrentAssets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('sumOfAssets', models.IntegerField()),
                ('sumOfDebtsAndFundsOwner', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BasicEarningsLossPerShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('basicEarningsOrLossPerShareFromContinuingOperationsOperating', models.IntegerField()),
                ('basicEarningsOrLossPerShareFromContinuingOperationsNonOperating', models.IntegerField()),
                ('basicEarningsOrLossPerShareFromDiscontinuingOperations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('netCashFlowsFromUsedInOperatingActivities', models.IntegerField()),
                ('netCashFlowsFromUsedInInvestmentReturnsAndPaymentsOnFinancingCosts', models.IntegerField()),
                ('incomeTaxesPaid', models.IntegerField()),
                ('netCashFlowsFromUsedInInvestingActivities', models.IntegerField()),
                ('netCashFlowsFromUsedInBeforeFinancingActivities', models.IntegerField()),
                ('netCashFlowsFromUsedInFinancingActivities', models.IntegerField()),
                ('netIncreaseDecreaseInCash', models.IntegerField()),
                ('cashAtEndOfPeriod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowsFromUsedInFinancingActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('proceedsFromIssuingShares', models.IntegerField()),
                ('proceedsFromSalesOrIssueOfTreasuryShares', models.IntegerField()),
                ('paymentsForPurchaseOfTreasuryShares', models.IntegerField()),
                ('proceedsFromBorrowingsClassifiedAsFinancingActivities', models.IntegerField()),
                ('repaymentsOfBorrowingsClassifiedAsFinancingActivities', models.IntegerField()),
                ('cashAtBeginningOfPeriod', models.IntegerField()),
                ('effectOfExchangeRateChangesOnCash', models.IntegerField()),
                ('NonCashTransactions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowsFromUsedInInvestingActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('proceedsFromSalesOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities', models.IntegerField()),
                ('purchaseOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities', models.IntegerField()),
                ('proceedsFromSalesOfIntangibleAssetsClassifiedAsInvestingActivities', models.IntegerField()),
                ('purchaseOfOnTangibleAssetsClassifiedAsInvestingActivities', models.IntegerField()),
                ('proceedsFromSalesOfNonCurrentInvestments', models.IntegerField()),
                ('facilitiesGrantedToIndividuals', models.IntegerField()),
                ('extraditionFacilitiesGrantedToIndividuals', models.IntegerField()),
                ('purchaseOfNonCurrentInvestments', models.IntegerField()),
                ('proceedsFromSalesOfCurrentInvestments', models.IntegerField()),
                ('purchaseOfCurrentInvestments', models.IntegerField()),
                ('proceedsFromSalesOfInvestmentProperty', models.IntegerField()),
                ('purchaseOfInvestmentProperty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowsFromUsedInOperatingActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('netCashFlowsFromUsedInOperatingActivitiesOrdinary', models.IntegerField()),
                ('netCashFlowsFromUsedInOperatingActivitiesExceptional', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowsUsedInIncomeTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('cash', models.IntegerField()),
                ('shortTermInvestments', models.IntegerField()),
                ('commercialInputs', models.IntegerField()),
                ('noncommercialInputs', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('prepaidExpenses', models.IntegerField()),
                ('salableAssets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentDebts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('commercialPayable', models.IntegerField()),
                ('NonCommercialPayable', models.IntegerField()),
                ('payableTaxes', models.IntegerField()),
                ('payableDividends', models.IntegerField()),
                ('financialFacility', models.IntegerField()),
                ('resources', models.IntegerField()),
                ('currentPreReceivables', models.IntegerField()),
                ('debtsRelatedWithSalableAssets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DebtsAndAssetsOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('sumOfCurrentDebts', models.IntegerField()),
                ('sumOfNonCurrentDebts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DilutedEarningsOrLossPerShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('dilutedEarningsOrLossPerShareFromContinuingOperationsOperating', models.IntegerField()),
                ('dilutedEarningsOrLossPerShareFromContinuingOperationsNonOperating', models.IntegerField()),
                ('dilutedEarningsOrLossPerShareFromDiscontinuingOperations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('grossProfit', models.IntegerField()),
                ('profitOrLossFromOperatingActivities', models.IntegerField()),
                ('profitOrLossBeforeTax', models.IntegerField()),
                ('profitLossFromContinuingOperations', models.IntegerField()),
                ('profitOrLoss', models.IntegerField()),
                ('basicEarningsLossPerShare', models.IntegerField()),
                ('dilutedEarningsLossPerShare', models.IntegerField()),
                ('adjustedRetainedEarningsBeginningBalance', models.IntegerField()),
                ('unallocatedRetainedEarningsAtTheBeginningOfPeriod', models.IntegerField()),
                ('distributableEarnings', models.IntegerField()),
                ('retainedEarningsAtEndOfPeriod', models.IntegerField()),
                ('earningsPerShareAfterTax', models.IntegerField()),
                ('listedCapital', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentReturnsAndPaymentsOnFinancingCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('dividendsReceived', models.IntegerField()),
                ('interestPaidOrBorrowing', models.IntegerField()),
                ('interestReceivedFromOtherInvestments', models.IntegerField()),
                ('dividendsPaid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonCurrentAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('longTermInvestments', models.IntegerField()),
                ('longTermInputs', models.IntegerField()),
                ('investmentInEstate', models.IntegerField()),
                ('intangibleAssets', models.IntegerField()),
                ('tangibleAssets', models.IntegerField()),
                ('otherAssets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonCurrentDebts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('longTermPayable', models.IntegerField()),
                ('nonCurrentPreReceivables', models.IntegerField()),
                ('longTermFinancialFacility', models.IntegerField()),
                ('storeOfWorkersEndServiceAdvantages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnerInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('assets', models.IntegerField()),
                ('increaseORDecreaseOfInProcessAssets', models.IntegerField()),
                ('stockSpends', models.IntegerField()),
                ('treasuryStocks', models.IntegerField()),
                ('legalSavings', models.IntegerField()),
                ('otherSavings', models.IntegerField()),
                ('RevaluationSurplusOfHeldForSaleAssets', models.IntegerField()),
                ('RevaluationSurplusOfAssets', models.IntegerField()),
                ('DifferenceInTheConvergenceDueToConversionToReportingCurrency', models.IntegerField()),
                ('ValuationAssetsOfAssetsAndLiabilitiesOfStateOwnedEnterprises', models.IntegerField()),
                ('accumulatedProfitORLosses', models.IntegerField()),
                ('sumOfOwnersInvestments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfitOrLoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('Revenue', models.IntegerField()),
                ('costOfSales', models.IntegerField()),
                ('distributionAndAdministrativeExpense', models.IntegerField()),
                ('otherIncome', models.IntegerField()),
                ('otherExpense', models.IntegerField()),
                ('financeCosts', models.IntegerField()),
                ('otherNonOperatingIncomeAndExpensesIncomeInvestments', models.IntegerField()),
                ('OtherNonOperatingIncomeAndExpensesMiscellaneousItems', models.IntegerField()),
                ('incomeTaxExpenseContinuingOperations', models.IntegerField()),
                ('profitOrLossFromDiscontinuedOperation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatementOfIncomeAndRetainedEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=2)),
                ('retainedEarningsAtBeginningOfPeriod', models.IntegerField()),
                ('priorPeriodAdjustments', models.IntegerField()),
                ('dividendsDeclaredAndPaidOrPayable', models.IntegerField()),
                ('changesInCapitalFromRetainedEarnings', models.IntegerField()),
                ('transferFromOtherEquityItems', models.IntegerField()),
                ('transferToStatutoryReserve', models.IntegerField()),
            ],
        ),
    ]
