# Generated by Django 2.2 on 2019-06-02 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatements',
            fields=[
                ('companyName', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('type_audit', models.CharField(choices=[('Y', 'حسابرسی شده'), ('N', 'حسابرسی نشده')], default='', max_length=1)),
                ('type_date', models.CharField(choices=[('3', 'ماهه 3'), ('6', 'ماهه 6'), ('9', 'ماهه 9'), ('12', 'ماهه 12')], default='', max_length=2)),
                ('type_consolidated', models.CharField(choices=[('Y', 'تلفیقی'), ('N', 'غیرتلفیقی')], default='', max_length=2)),
                ('endTo', models.DateField(default=django.utils.timezone.now, verbose_name='End to')),
            ],
        ),
    ]
