# Generated by Django 2.2 on 2019-05-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='type_audit',
            field=models.CharField(choices=[('Y', 'حسابرسی شده'), ('N', 'حسابرسی نشده')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='type_date',
            field=models.CharField(choices=[('3', '3 ماهه'), ('6', '12 ماهه'), ('9', 'حسابرسی شده'), ('12', 'حسابرسی نشده')], default=0, max_length=2),
        ),
    ]
