# Generated by Django 2.2 on 2019-05-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0002_auto_20190524_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='type_date',
            field=models.CharField(choices=[('3', 'ماهه 3'), ('6', 'ماهه 6'), ('9', 'ماهه 9'), ('12', 'ماهه 12')], default=0, max_length=2),
        ),
    ]
