# Generated by Django 2.2.1 on 2019-05-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0002_auto_20190509_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='publicDate',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='publicDate',
        ),
        migrations.RemoveField(
            model_name='currentassets',
            name='publicDate',
        ),
        migrations.RemoveField(
            model_name='debtsandassetsowner',
            name='publicDate',
        ),
    ]
