# Generated by Django 2.2 on 2019-06-02 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0002_financialstatements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='publicDate',
        ),
        migrations.AddField(
            model_name='company',
            name='endTo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End to'),
        ),
        migrations.AddField(
            model_name='company',
            name='type_audit',
            field=models.CharField(choices=[('Y', 'حسابرسی شده'), ('N', 'حسابرسی نشده')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='company',
            name='type_consolidated',
            field=models.CharField(choices=[('Y', 'تلفیقی'), ('N', 'غیرتلفیقی')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='company',
            name='type_date',
            field=models.CharField(choices=[('3', 'ماهه 3'), ('6', 'ماهه 6'), ('9', 'ماهه 9'), ('12', 'ماهه 12')], default='', max_length=2),
        ),
    ]
