# Generated by Django 2.2.1 on 2019-05-09 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0003_auto_20190509_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtsandassetsowner',
            name='publicDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 9, 37, 23, 140991, tzinfo=utc), verbose_name='Data published'),
            preserve_default=False,
        ),
    ]
