# Generated by Django 2.2 on 2019-05-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0003_auto_20190524_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='endTo',
            field=models.DateTimeField(default=0, verbose_name='End to:'),
        ),
    ]
