# Generated by Django 2.2 on 2019-06-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0004_auto_20190626_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='basicearningslosspershare',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='cashflowsfromusedinfinancingactivities',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='cashflowsfromusedininvestingactivities',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='cashflowsfromusedinoperatingactivities',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='currentassets',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='currentdebts',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='debtsandassetsowner',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='dilutedearningsorlosspershare',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='investmentreturnsandpaymentsonfinancingcosts',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='mymodel0',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='mymodel1',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='noncurrentassets',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='noncurrentdebts',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='ownerinvestment',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='profitorloss',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
        migrations.AlterField(
            model_name='statementofincomeandretainedearnings',
            name='relatedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bourse.FinancialStatements', verbose_name='مربوط به'),
        ),
    ]
