# Generated by Django 2.2 on 2019-05-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0004_balancesheet_endto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='endTo',
            field=models.DateTimeField(verbose_name='End to:'),
        ),
    ]
