# Generated by Django 2.2.1 on 2019-05-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0004_debtsandassetsowner_publicdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtsandassetsowner',
            name='publicDate',
        ),
    ]
