# Generated by Django 2.2 on 2019-05-24 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0005_auto_20190524_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='endTo',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End to:'),
        ),
    ]
