# Generated by Django 2.2 on 2019-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0008_auto_20190524_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='type_consolidated',
            field=models.CharField(choices=[('Y', 'تلفیقی'), ('N', 'غیرتلفیقی')], default=0, max_length=2),
        ),
    ]
